#!/usr/bin/env python3
"""Embed SPIR-V binaries as deterministic uint32_t C++ arrays."""

from __future__ import annotations

import re
import struct
import sys
from pathlib import Path


def identifier(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_]", "_", name)
    value = re.sub(r"_+", "_", value).strip("_") or "data"
    return "matter_spirv_" + value


def cpp_string_literal(value: str) -> str:
    """Return an execution-encoding-independent C++ literal for a filename."""
    return '"' + "".join(f"\\x{byte:02x}" for byte in value.encode("utf-8")) + '"'


def render(inputs: list[Path]) -> str:
    entries: list[tuple[str, str, tuple[int, ...]]] = []
    identifiers: set[str] = set()
    names: set[str] = set()
    for path in sorted(inputs, key=lambda item: item.name):
        data = path.read_bytes()
        if len(data) % 4 != 0:
            raise ValueError(
                f"{path}: SPIR-V byte length {len(data)} is not divisible by 4"
            )
        name = path.name
        symbol_base = identifier(name)
        symbol = symbol_base
        suffix = 2
        while symbol in identifiers:
            symbol = f"{symbol_base}_{suffix}"
            suffix += 1
        if name in names:
            raise ValueError(f"duplicate embedded SPIR-V lookup name: {name}")
        names.add(name)
        identifiers.add(symbol)
        words = struct.unpack(f"<{len(data) // 4}I", data)
        entries.append((name, symbol, words))

    lines = [
        "// Generated by tools/embed_spirv.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace matter {",
        "struct EmbeddedSpirvView {",
        "    const uint32_t* words;",
        "    size_t word_count;",
        "};",
        "",
    ]
    for _, symbol, words in entries:
        lines.append(f"inline constexpr uint32_t {symbol}[] = {{")
        for start in range(0, len(words), 8):
            chunk = words[start : start + 8]
            lines.append("    " + ", ".join(f"0x{word:08x}u" for word in chunk) + ",")
        lines.extend(["};", ""])
    lines.append("inline EmbeddedSpirvView find_spirv(std::string_view name) {")
    for name, symbol, _ in entries:
        lines.append(
            f"    if (name == {cpp_string_literal(name)}) return "
            f"{{{symbol}, sizeof({symbol}) / sizeof({symbol}[0])}};"
        )
    lines.extend(["    return {nullptr, 0};", "}", "", "}  // namespace matter", ""])
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(f"usage: {argv[0]} OUTPUT INPUT.spv [INPUT.spv ...]", file=sys.stderr)
        return 2
    output = Path(argv[1])
    try:
        content = render([Path(value) for value in argv[2:]])
    except (OSError, ValueError) as exc:
        print(f"embed_spirv.py: error: {exc}", file=sys.stderr)
        return 1
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text(encoding="utf-8") != content:
        output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
