#!/usr/bin/env python3
"""embed_shaders.py <out_header> <base_dir> <logical_path>...
Reads <base_dir>/<logical_path> for each entry, emits a C++ header embedding
the text as escaped string literals keyed by logical path."""
import sys, os

def c_escape(text):
    out = []
    for line in text.split("\n"):
        e = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'"{e}\\n"')
    return "\n    ".join(out)

def main():
    out_path, base = sys.argv[1], sys.argv[2]
    entries = []
    for lp in sys.argv[3:]:
        src = os.path.join(base, lp)
        with open(src, "r") as f:
            entries.append((lp, f.read()))
    with open(out_path, "w") as f:
        f.write("// GENERATED by tools/embed_shaders.py — do not edit.\n")
        f.write("#pragma once\n\nnamespace matter_embedded {\n")
        f.write("struct Entry { const char* path; const char* text; };\n")
        for i, (lp, text) in enumerate(entries):
            f.write(f"inline const char* kText{i} =\n    {c_escape(text)};\n")
        f.write("inline const Entry kEmbeddedShaders[] = {\n")
        for i, (lp, _) in enumerate(entries):
            f.write(f'    {{ "{lp}", kText{i} }},\n')
        f.write("};\n")
        f.write(f"inline const int kEmbeddedShaderCount = {len(entries)};\n")
        f.write("} // namespace matter_embedded\n")

if __name__ == "__main__":
    main()
