#version 450

#include "gpu_mesh_common.glsl"

layout(local_size_x = 256) in;
layout(std430, binding = 0) readonly buffer ParamsBuffer {
    uvec4 params;
};
layout(std430, binding = 1) buffer OutputBuffer {
    uint values[];
} outputBuffer;
layout(std430, binding = 2) readonly buffer BlockOffsetsBuffer {
    uint values[];
} blockOffsetsBuffer;

void main() {
    const uint element = gl_GlobalInvocationID.x;
    if (element >= params.x) return;
    outputBuffer.values[element] +=
        blockOffsetsBuffer.values[element / 256u];
}
