#include "part_workbench_iso.h"

#include <cctype>
#include <sstream>

namespace viewer {

std::string workbench_iso_identifier(const std::string& module) {
    std::string out;
    out.reserve(module.size());
    for (char c : module) {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
            out += c;
        else
            out += '_';
    }
    if (out.empty() || std::isdigit(static_cast<unsigned char>(out[0])))
        out = "_" + out;
    return out;
}

std::string workbench_iso_world_source(const std::string& module,
                                       const std::string& params_json) {
    const std::string class_name = "IsoWorld_" + workbench_iso_identifier(module);
    std::ostringstream js;
    js << "// Generated by the Part Workbench (part-workbench.md W2). Safe to\n"
       << "// delete; rewritten on every open/param edit/bake.\n"
       << "class " << class_name << " extends World {\n"
       << "  static roots = [{\n"
       << "    module: \"" << module << "\",\n"
       << "    params: " << params_json << ",\n"
       << "    transform: [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1],\n"
          // expand stays false: expansion replaces the root with its children
          // and hard-fails on leaf parts, publishing nothing (see the header
          // note). The part composes its requires-children at bake exactly as
          // an authored world root does.
       << "    expand: false,\n"
       << "  }];\n"
       << "}\n";
    return js.str();
}

}  // namespace viewer
