// MatterEditor/src/part_workbench_iso.cpp
//
// The generated text is CONTRACT, not formatting: the bake pipeline parses it
// verbatim through the QuickJS script host, so a change here changes what the
// workbench actually bakes. See the rationale for the `expand: false` field —
// and the defect that pinned it — in part_workbench_iso.h.
//
// Written to disk by PartWorkbench::write_iso_world_file() on every open, on
// every params edit, and on every bake, into
// `<scratch_project>/worlds/__iso_<module>.js`.
#include "part_workbench_iso.h"

#include <cctype>
#include <sstream>

namespace viewer {

// Two rules, both required by JavaScript identifier syntax: every character
// that is not [A-Za-z0-9_] becomes '_', and a name that is empty or starts
// with a digit is prefixed with '_'. The mapping is deliberately NOT
// injective — "My-Part" and "My_Part" collapse to the same identifier — which
// is acceptable only because the result also names the isolation world and
// its scratch cache, so a collision means two similarly-named modules share a
// scratch directory rather than producing invalid JS.
std::string workbench_iso_identifier(const std::string& module) {
    std::string out;
    out.reserve(module.size());
    for (char c : module) {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
            out += c;
        else
            out += '_';
    }
    if (out.empty() || std::isdigit(static_cast<unsigned char>(out[0])))
        out = "_" + out;
    return out;
}

std::string workbench_iso_world_source(const std::string& module,
                                       const std::string& params_json) {
    const std::string class_name = "IsoWorld_" + workbench_iso_identifier(module);
    std::ostringstream js;
    js << "// Generated by the Part Workbench (part-workbench.md W2). Safe to\n"
       << "// delete; rewritten on every open/param edit/bake.\n"
       << "class " << class_name << " extends World {\n"
       << "  static roots = [{\n"
       << "    module: \"" << module << "\",\n"
       << "    params: " << params_json << ",\n"
       << "    transform: [1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1],\n"
          // expand stays false: expansion replaces the root with its children
          // and hard-fails on leaf parts, publishing nothing (see the header
          // note). The part composes its requires-children at bake exactly as
          // an authored world root does.
       << "    expand: false,\n"
       << "  }];\n"
       << "}\n";
    return js.str();
}

}  // namespace viewer
