#!/usr/bin/env python3
"""embed_rt_shaders.py <out_header> <ptx_file>...
Embeds PTX files as C string constants in a header."""
import sys, os

def c_escape(text):
    out = []
    for line in text.split("\n"):
        e = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'"{e}\\n"')
    return "\n    ".join(out)

def to_var_name(path):
    """shadow_raygen.ptx -> shadow_raygen_ptx"""
    return os.path.basename(path).replace(".", "_")

def main():
    out_path = sys.argv[1]
    entries = []
    for ptx_path in sys.argv[2:]:
        with open(ptx_path, "r") as f:
            entries.append((to_var_name(ptx_path), f.read()))
    with open(out_path, "w") as f:
        f.write("// GENERATED by tools/embed_rt_shaders.py — do not edit.\n")
        f.write("#pragma once\n\n")
        f.write("#ifdef MATTER_HAVE_OPTIX\n\n")
        f.write("namespace matter_rt_embedded {\n\n")
        for var, text in entries:
            f.write(f"inline const char {var}[] =\n    {c_escape(text)};\n\n")
        f.write("} // namespace matter_rt_embedded\n\n")
        f.write("#endif // MATTER_HAVE_OPTIX\n")

if __name__ == "__main__":
    main()
