#!/usr/bin/env python3
"""Embed one PTX module as a deterministic null-terminated byte array."""

from __future__ import annotations

import sys
from pathlib import Path


def render(source: Path) -> str:
    data = source.read_bytes() + b"\0"
    lines = [
        "// Generated by tools/physx/embed-ptx.py. Do not edit.",
        "#pragma once",
        "",
        "namespace matter_physx {",
        "inline constexpr unsigned char kFillSensorPtx[] = {",
    ]
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend([
        "};",
        "}  // namespace matter_physx",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} OUTPUT INPUT.ptx", file=sys.stderr)
        return 2
    output = Path(argv[1])
    try:
        content = render(Path(argv[2]))
        output.parent.mkdir(parents=True, exist_ok=True)
        if not output.exists() or output.read_text(encoding="utf-8") != content:
            output.write_text(content, encoding="utf-8", newline="\n")
    except OSError as error:
        print(f"embed-ptx.py: error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
